### ISSUE TITLE
code for "Learning Optimal Conformal Classifiers".

### ISSUE THREAD

**Issue by ChenxuZhao0** [ml-stat-Sustech/TorchCP#11]
Hi Jianguo,

Great work! I'm interested to know if you have implemented the code for "Learning Optimal Conformal Classifiers"?

**Comment by Jianguo99** [comment]
Yes. The implementation codes can be found in the torchcp.classification,loss.conftr. Additionally, a training example has been included in the file named "conformal_training.py" located in the “examples” folder.

**Comment by ChenxuZhao0** [comment]
Thank you so much!
