### ISSUE TITLE
Conformal prediction对文本分类的积极作用

### ISSUE THREAD

**Issue by yoloxbb** [ml-stat-Sustech/TorchCP#21]
想利用这个包对深度学习模型应用于文本分类的输出结果进行共形预测，但是不知道如何调整

**Comment by hongxin001** [comment]
You may refer to the example presented in the README document. And you can find more examples in the examples folder.

**Comment by yoloxbb** [comment]
> 您可以参考 README 文档中提供的示例。您可以在示例文件夹中找到更多示例。

好的，找到了，已经成功运行了，谢谢
