### ISSUE TITLE
Conformal Prediction beyond Exchangeability

### ISSUE THREAD

**Issue by tingyushi** [ml-stat-Sustech/TorchCP#24]
Hello,

Thank you for this helpful toolbox!

I saw that you have implemented weighted conformal predictor based on the paper "Conformal Prediction Under Covariate Shift". 

However, is this the same as the non-exchangeable conformal prediction/risk control as described in the following papers?
* [Conformal Prediction Beyond Exchangeability](https://arxiv.org/abs/2202.13415)
* [Non-Exchangeable Conformal Risk Control](https://arxiv.org/abs/2310.01262)

Thanks!!
Tingyu Shi

**Comment by Jianguo99** [comment]
Dear Tingyu Shi，

Sorry for the late response. The weighted conformal prediction is not the same as non-exchangeable conformal prediction. The non-exchangeable conformal prediction proposed fixed weights, but weighted conformal prediction uses the data-dependent weights.

Please let us know if you have more questions.

Best regards,
authors
