### ISSUE TITLE
Non-Scalar output

### ISSUE THREAD

**Issue by Naor-F** [ml-stat-Sustech/TorchCP#26]
Hello, 

I'm attempting to utilize the toolbox for a non-scalar output regression task. Do you have an example I could refer to? 

Thanks,

**Comment by Jianguo99** [comment]
Dear [Naor-F](https://github.com/Naor-F),

For vector-valued models, you can apply CP to each element individually.

Please let me know if you have any further questions or if there is anything else I can assist you with.

Best regards,
authors

**Comment by Jianguo99** [comment]
Dear Naor-F,

Thank you for your message. Could you please clarify whether the length of the predictive period is fixed? If it is, we can apply CP for the same future time point.

Please let me know if my understanding is incorrect. I look forward to your response.

Best regards,
authors

**Comment by Naor-F** [comment]
Hi,

The input consists of N points, and the output consists of M points representing future time: t+1, t+2, ..., t+M. I am predicting M points into the future. 

You recommend applying CP to each point separately.

Best regards,

**Comment by Jianguo99** [comment]
Dear Naor-F,

I think your problem setup should be using the first N moments to predict the subsequent M moments. With different inputs, the outputs might have overlapping parts. Therefore, it is unreasonable to apply CP to each output value individually.

If this is the case, you might try to average the overlapping parts to implement the standard CP algorithm, including the calibration process and the prediction process (This is my guess and might be difficult to satisfy valid coverage). 

Finally, my key suggestion is to run a numerical experiment and see if you might gain additional insights. Looking forward to your response.

Best regards,
authors

**Comment by Naor-F** [comment]
Hi,

Thank you very much for taking time to think about this. Very appreciated.

I will dive into this topic, and see what is the right approach for this
kind of problem.

Regards,
